# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreshInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftitle', models.CharField(max_length=32)),
                ('fpic', models.ImageField(upload_to='fresh_info')),
                ('fprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('funit', models.CharField(default='500g', max_length=32)),
                ('fclick', models.IntegerField()),
                ('fsynopsis', models.CharField(max_length=200)),
                ('fcontent', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='FreshType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='freshinfo',
            name='ftype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_home.FreshType'),
        ),
    ]
