# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_home', '0003_auto_20171218_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshtype',
            name='tentitle',
            field=models.CharField(default='firut', max_length=32),
        ),
    ]
