# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ureceiver', models.CharField(max_length=32)),
                ('uaddress', models.CharField(max_length=64)),
                ('uphone', models.CharField(max_length=11)),
                ('current_addr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32)),
                ('upwd', models.CharField(max_length=64)),
                ('uemail', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='useraddr',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo'),
        ),
    ]
