# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_home', '0004_freshtype_tentitle'),
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfresh_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_home.FreshInfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ushopping_cart',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='suser_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo'),
        ),
    ]
