# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_auto_20171220_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='sfresh_info',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='suser_info',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
