# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20171220_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ushopping_cart',
        ),
    ]
