# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_home', '0004_freshtype_tentitle'),
        ('df_user', '0003_auto_20171220_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snum', models.IntegerField()),
                ('sfresh_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_home.FreshInfo')),
                ('suser_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo')),
            ],
        ),
    ]
