# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171117_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='news',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='notic',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='task',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
