# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171117_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fabulous',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='file_path',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='opposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
