# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171117_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='comm',
            name='comm_abstract',
            field=models.CharField(max_length=255),
        ),
    ]
