# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171118_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_img',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_img',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
