# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171124_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introduce_oneself',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
