# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20171124_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='introduce_oneself',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
