# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20171124_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_to_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Classification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
    ]
