# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_user_to_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_to_class',
            name='article_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
