# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0004_remove_userinfo_ushopping_cart'),
        ('df_home', '0004_freshtype_tentitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocount', models.IntegerField()),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ogoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_home.FreshInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otime', models.DateTimeField(auto_now=True)),
                ('oIspay', models.BooleanField(default=False)),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oaddr', models.CharField(max_length=200)),
                ('ouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='oorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_order.OrderInfo'),
        ),
    ]
